### PR TITLE
MineClonia/MineClone2 support

### PR DESCRIPTION
**Pull request by nonfreegithub**
This mod works in MTG, MineClonia and MineClone2 games.

### CODE REVIEW

**Comment by Skandarella** [comment]
So far so good, but there are some problems.

I got an error message from mod mobs:

2023-12-22 13:50:15: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod '??' in callback luaentity_Step(): F:\minetest-5.6.1-win64\bin\..\mods\mobs/api.lua:1254: attempt to index local 'nodt' (a nil value)
2023-12-22 13:50:15: ERROR[Main]: stack traceback:
2023-12-22 13:50:15: ERROR[Main]: 	F:\minetest-5.6.1-win64\bin\..\mods\mobs/api.lua:1254: in function 'do_jump'
2023-12-22 13:50:15: ERROR[Main]: 	F:\minetest-5.6.1-win64\bin\..\mods\mobs/api.lua:3543: in function 'on_step_old'
2023-12-22 13:50:15: ERROR[Main]: 	...mes\mineclone2\mods\ENVIRONMENT\mcl_void_damage\init.lua:24: in function <...mes\mineclone2\mods\ENVIRONMENT\mcl_void_damage\init.lua:23>
2023-12-22 13:50:16: ACTION[Server]: [doc] Wrote player data into F:\minetest-5.6.1-win64\bin\..\worlds\deffsd/doc.mt.
2023-12-22 13:50:16: ACTION[Server]: singleplayer leaves game. List of players: 
2023-12-22 13:50:16: WARNING[Server]: ScriptApiBase::objectrefGetOrCreate(): Pushing ObjectRef to removed/deactivated object, this is probably a bug.
2023-12-22 13:50:16: ACTION[Main]: Server: Shutting down
2023-12-22 13:50:16: ACTION[Main]: [doc] Server shuts down. Player data is about to be saved.
2023-12-22 13:50:16: ACTION[Main]: [doc] Wrote player data into F:\minetest-5.6.1-win64\bin\..\worlds\deffsd/doc.mt.

**Comment by Skandarella** [comment]
I have updated the animals, also added spawn neighbor nodes and food from Mcl2 and Mineclonia to feed them. You can test it.

**Comment by nonfreegithub** [comment]
> So far so good, but there are some problems.
> 
> I got an error message from mod mobs:

how you get this error?

**Comment by nonfreegithub** [comment]
> I have updated the animals, also added spawn neighbor nodes and food from Mcl2 and Mineclonia to feed them. You can test it.

works!

**Pull request closed without merging**
